WEB_SCHEMA = "https"

LOCAL_SCHEMA = "http"
LOCAL_BASE_DOMAIN = "0.0.0.0"
LOCAL_DEFAULT_PORT = "8080"

MAX_RETRIES = 3

PROD = "prod"
STAGING = "staging"
DEV = "dev"
CI = "ci"

ENV_ABBR_TO_ENV_MAP = {"p": PROD, "s": STAGING, "d": DEV}

ENV_TO_DOMAIN_MAP = {
    PROD: "plenty.tools",
    STAGING: "plenty-staging.tools",
    DEV: "plenty-dev.tools",
    CI: "plenty-dev.tools",
}

PLENTY_API_KEY = "BFF_PLENTY_API_KEY"
PLENTY_API_SECRET = "BFF_PLENTY_API_SECRET"
ENVIRONMENT_CONTEXT = "ENVIRONMENT_CONTEXT"
IN_KUBERNETES = "IN_KUBERNETES"
URL_SUFFIX = "_URL"
GOOGLE_SHEET_AUTH = "GOOGLE_SHEET_AUTH"
AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"
SERVICE_NAME = "DD_SERVICE_NAME"
CALLER_HEADER = "X-Caller-Name"
